### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by TheStarSlayer** [TheStarSlayer/HammingCode#1]
Code is not that readable and could use refactoring...

**Comment by TheStarSlayer** [comment]
Closed issue after refactoring code

**Comment by falgunchugh** [comment]
you can still further break down the code and make it more readable and also accessible to other functions in future

**Comment by TheStarSlayer** [comment]
> you can still further break down the code and make it more readable and also accessible to other functions in future

I wasn't expecting anyone to see these, haha. Thank you for looking and giving your kind advice😊

**Comment by falgunchugh** [comment]
sure 😊 and I actually refactored it, If you want to check it out I can create a PR

**Comment by TheStarSlayer** [comment]
Sure, please do.
